package digitalmarketing.MarketModel;

import digitalmarketing.Business.Business;

import java.util.ArrayList;
import java.util.Collections;

public class AdSetsReport {

    Business business;
    ArrayList<AdSetSummary> adSetSummaries;

    // Constructor
    public AdSetsReport(Business b) {
        this.business = b;
        adSetSummaries = new ArrayList<>();
        for (AdSet as : b.getAdSetDirectory().getAdSets()) {
            adSetSummaries.add(new AdSetSummary(as));
        }
    }

    public void sortByRank() {
        Collections.sort(adSetSummaries, new AdSetSummaryComparator());
    }


    // Output
    public void printTopRank() {
        System.out.println("--------------------------- Ad Sets Report ----------------------------");
        System.out.println("                       Sorted By: Sales Revenue                    ");
        sortByRank();

        for(int i = 0; i < adSetSummaries.size(); i++) {
            System.out.print("#" + (i + 1) + " ");
            adSetSummaries.get(i).printDetails();
        }

        System.out.println();
        System.out.println("Indicator Descriptions:");
        System.out.println("* Order Quantity = total count of orders generated by the ad");
        System.out.println("* Order Revenue = total orders revenue generated by the ad");
        System.out.println("* Total Cost = Cost Per Sale × Order Quantity");
        System.out.println();
    }
}
